### ISSUE TITLE
Layouts and left menu not working

### ISSUE THREAD

**Issue by eSaner** [g-kanoufi/genesis-foundation6-child-theme#1]
Hi. Thanks for putting this together; well done! When I install the theme (and also on your demo) only the content-sidebar layout seems to work. Should the other layouts be working?

Also, when I assign a menu to the Left Menu, nothing shows up.

**Comment by g-kanoufi** [comment]
Hi there,

Layouts should be working, as on the demo: http://demo-foundation-6.lostwebdesigns.com/portfolio/sidebar-content/ for example.

The left menu, might not be totally integrated right now. But i will fix this while updating foundation to 6.2 later next week.

Please let me know if the layouts are not working properly, and don't hesitate to send me any url with the issue.

Thanks

**Comment by eSaner** [comment]
The demo page you linked to demonstrates the issue. It is titled Sidebar content, but it displays content sidebar. The same issue exists on Content sidebar sidebar and Sidebar content sidebar. The only layout that displays is content sidebar. See attached screenshots, also.
![foundesis-content-sidebar-sidebar](https://cloud.githubusercontent.com/assets/6232891/13383317/d5c328f0-de55-11e5-9f4b-f47be7e2ba14.jpg)
![foundesis-sidebar-content](https://cloud.githubusercontent.com/assets/6232891/13383318/d5c773b0-de55-11e5-92a7-812a84464278.jpg)

**Comment by g-kanoufi** [comment]
Sorry about that,

I will look into that this week and push some changes when it’s fixed.

Thank you for letting me know though.

Have a nice week,

-- 
Guillaume Kanoufi

On February 29, 2016 at 01:00:58, eSaner (notifications@github.com) wrote:

The demo page you linked to demonstrates the issue. It is titled Sidebar content, but it displays content sidebar. The same issue exists on Content sidebar sidebar and Sidebar content sidebar. The only layout that displays is content sidebar. See attached screenshots, also.

**Comment by g-kanoufi** [comment]
Hey @eSaner, would you mind, cloning the new pushed theme. I have updated .bowerrc to get the latest foundation 6 version and it seems to work properly now, at least on the demo, would you mind telling me if this is ok for you now?

Thanks,

**Comment by eSaner** [comment]
The page layouts work for me now. Thanks!

The Left Top Bar menu still doesn't appear. I also got some errors running gulp. See attached. Did normalize get removed in the update?
[gulp-errors.txt](https://github.com/g-kanoufi/genesis-foundation6-child-theme/files/157078/gulp-errors.txt)

**Comment by g-kanoufi** [comment]
Awesome, 

Thanks for letting me know.

Cheers,
